/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2019-07-08 06:13:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.department;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class input_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1560908344000L));
    _jspx_dependants.put("/WEB-INF/department/../common/header.jsp", Long.valueOf(1561528495077L));
    _jspx_dependants.put("/WEB-INF/department/../common/menu.jsp", Long.valueOf(1561523552539L));
    _jspx_dependants.put("/WEB-INF/department/../common/top.jsp", Long.valueOf(1560922390000L));
    _jspx_dependants.put("jar:file:/C:/Users/cwlojako/Desktop/apache-tomcat-8.0.47/webapps/ROOT/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425949870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>叩丁狼教育-JavaWEB综合案例</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/js/plugins/bootstrap/css/bootstrap.css\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/core.css\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/plugins/jquery/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/plugins/bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/layui/layui.js\"></script>\r\n");
      out.write("<!-- 分页插件 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/plugins/page/jquery.twbsPagination2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container \" style=\"margin-top: 20px\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("     .lg2 {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 26px;\r\n");
      out.write("        left: 150px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"navbar cm-navbar\">\r\n");
      out.write("    <img class=\"logo\" alt=\"Brand\" src=\"/images/logo.png\">\r\n");
      out.write("    <img src=\"/images/logo1.png\" class=\"lg2\">\r\n");
      out.write("    <span class=\"pageTitle\">&nbsp;</span>\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right cm-navbar-nav \">\r\n");
      out.write("        <li>\r\n");
      out.write("           <p class=\"navbar-text text-info\">用户: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${USER_IN_SESSION.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a href=\"/logout\">安全退出</a></li>\r\n");
      out.write("        <li><a href=\"\">个人设置</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t<br /> <br />\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<ul id=\"menu\" class=\"list-group\">\r\n");
      out.write("\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t<a href=\"#\" data-toggle=\"collapse\" data-target=\"#strategy_detail\">\r\n");
      out.write("\t\t\t<span>系统管理</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<ul class=\"in\" id=\"strategy_detail\">\r\n");
      out.write("            <li class=\"employee\"><a href=\"/employee\">员工管理</a></li>\r\n");
      out.write("\t\t\t<li class=\"department\"><a href=\"/department\">部门管理</a></li>\r\n");
      out.write("\t\t\t<li class=\"permission\"><a href=\"/permission\">权限管理</a></li>\r\n");
      out.write("\t\t\t<li class=\"role\"><a href=\"/role\">角色管理</a></li>\r\n");
      out.write("\t\t\t<li class=\"\"><a href=\"#\">研发中......</a></li>\r\n");
      out.write("\t\t\t<li class=\"\"><a href=\"#\">研发中......</a></li>\r\n");
      out.write("\t\t\t<li class=\"\"><a href=\"#\">研发中......</a></li>\r\n");
      out.write("\t\t\t<li class=\"\"><a href=\"#\">研发中......</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar url = location.pathname;\r\n");
      out.write("\turl = url.substring(1);\r\n");
      out.write("\r\n");
      out.write("    $(\".in li.\"+url).addClass(\"active\");\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t<div class=\"row col-sm-10\">\r\n");
      out.write("\t\t\t\t\t<form class=\"form-horizontal\" action=\"/department?cmd=saveOrUpdate\"\r\n");
      out.write("\t\t\t\t\t\tmethod=\"post\" id=\"editForm\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dept.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"id\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"name\" class=\"col-sm-2 control-label\">部门名称</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dept.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"请输入部门名称\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"sn\" class=\"col-sm-2 control-label\">部门英名</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"sn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dept.sn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"sn\" placeholder=\"请输入部门英文名\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-offset-1 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"btn_submit\" type=\"submit\" class=\"btn btn-default\">保存</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"reset\" class=\"btn btn-default\">重置</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
